### PR TITLE
 Merge branch 'master' from advdev repo to isi-sdk

### PR DESCRIPTION
**Pull request by bishopw**
- This is Alex's 'Fix for "required" parameters' patch, from his
   original PR notes:

 - Now the converter takes into account the list of "required"
   parameters when determining if it needs to create a new data model
   definition or reuse an old one or when trying to find an existing
   data model definition that it can extend. This prevents certain data
   model definitions from having more required parameters than they are
   supposed to.

 - Also, I created a new Swagger Codegen template, by modifying the
   existing one from the Swagger Codegen source, that takes into account
   whether or not the parameter is required when validating the
   parameter's input value (this actually seems like a bug in the
   template, so perhaps we should submit it upstream to the Swagger
   Codegen project).

 - I also updated the code so that "Response" objects (i.e. data model
   definitions) don't make parameters that can be either "null" or a
   "string" (or some other non-null data type) required. This along with
   the update to the Codegen template fixes issues with the
   /cluster/config and /quota/quoats end points, in particular, where a
   perfectly correct response from the PAPI was getting rejected
   because of null values in the response, that the PAPI says is
   "required", but are allowed to be null because they are a multi-type
   parameter.

### CODE REVIEW

**Comment by bishopw** [comment]
(Closing and reopening to check unit test automation setup.)

**Comment by bishopw** [comment]
(Reopening to check unit test automation setup.)

**Comment by dmoxon** [comment]
LGTM

**Comment by apecoraro** [comment]
In order for these fixes to work it requires that the Swagger Codegen is run with the custom template that I added to the swagger_templates directory. Is the automated build system set up to do that?

**Comment by cbrainerd** [comment]
The automated build doesn't do anything specifically to use the custom template. The invocation of swagger-codegen follows basically the pattern laid out in [readme.dev.md](https://github.com/Isilon/isilon_sdk/blob/master/readme.dev.md#to-generate-papi-bindings-for-python-or-other-languages-using-the-swagger-config). 

Does the custom template need to be specified during invocation of codegen?

**Pull request merged**
